# Generated by Django 5.2.8 on 2025-11-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0003_phoneotp_profile_is_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('worker', 'Worker'), ('provider', 'Provider')], max_length=20),
        ),
    ]
