# Generated by Django 5.2.8 on 2025-11-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0005_booking_date_booking_user_booking_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default.png', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('provider', 'Provider'), ('service_seeker', 'Service Seeker')], max_length=20),
        ),
    ]
