# Generated by Django 5.2.8 on 2025-11-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0006_profile_profile_image_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('welder', 'Welder'), ('plumber', 'Plumber'), ('painter', 'Painter'), ('electrician', 'Electrician'), ('carpenter', 'Carpenter'), ('bike_mechanic', 'Bike Mechanic'), ('car_mechanic', 'Car Mechanic'), ('tyre_repair', 'Tyre Repairman'), ('waste_collector', 'Waste Collector'), ('pest_control', 'Pest Control'), ('cleaning', 'Cleaning Service'), ('gardening', 'Gardening Service'), ('painting', 'Painting Service'), ('moving', 'Moving Service'), ('delivery', 'Delivery Service'), ('tutor', 'Tutor'), ('driver', 'Driver'), ('chef', 'Chef'), ('babysitter', 'Babysitter'), ('maid', 'Maid'), ('security_guard', 'Security Guard'), ('photographer', 'Photographer'), ('event_planner', 'Event Planner'), ('other', 'Other')], max_length=30),
        ),
    ]
