# Generated by Django 5.2.8 on 2025-11-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0013_remove_wallettransaction_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='radius_km',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='radius',
            field=models.IntegerField(default=5),
        ),
    ]
