# Generated by Django 5.2.8 on 2025-11-23 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0016_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_bookings', to='job_app.profile')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_seeker_bookings', to='job_app.profile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_service_bookings', to='job_app.service')),
            ],
        ),
        migrations.CreateModel(
            name='SeekerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_bookings', to='job_app.profile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_service_bookings', to='job_app.service')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
